branches:
  only:
  - build

language: node_js
node_js: '11'

before_install: ".travis/before_install.sh $encrypted_cb753b59ae60_key $encrypted_cb753b59ae60_iv"

install: true

script: ".travis/build.sh"

deploy:
  provider: script
  script: ".travis/deploy.sh"
  skip_cleanup: true
