branches:
  only:
  - build

git:
  submodules: false

language: node_js
node_js: '11'

before_install: ".travis/before_install.sh $encrypted_f217180e22ee_key $encrypted_f217180e22ee_iv"

install: true

script: ".travis/build.sh"

deploy:
  provider: script
  script: ".travis/deploy.sh $encrypted_f217180e22ee_key $encrypted_f217180e22ee_iv"
  skip_cleanup: true
  on:
    branch: build
