name: Dependency version check
on:
  schedule:
    - cron: '0 2 * * 1,3,5'
  push:
    branches: [ build ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'build'
    - name: Install NCU
      run: npm install -g npm-check-updates
    - name: Check dependency versions
      run: ncu | grep 'All dependencies match the latest package versions'
