name: Release

on:
  push:
    branches: [ build ]

jobs:
  build_test_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'build'
      - name: Checkout release-dir
        uses: actions/checkout@v2
        with:
          ref: 'main'
          path: dist
      - name: Clean dist
        run: rm -rf dist/*
      - uses: actions/setup-node@v2
        with:
          node-version: '^v14.4.0'
      - name: Install
        run: npm install
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Commit & Push
        run: |
          cd dist
          git config user.email "3663856+jensim@users.noreply.github.com"
          git config user.name "GitHub Actions on behalf of Jens Brimfors"
          git add -A
          git commit -m 'Updated site from GitHub Actions'
          git push origin
